eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetchRegistry: false

server:
  port: 8761
#eureka.client.server.waitTimeInMsWhenSyncEmpty=0
